---

- name: Configure plymouth
  template:
    src: plymouthd.conf.j2
    dest: "{{ plymouth__config_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Get service facts
  service_facts:

- name: Find active display manager
  set_fact:
    display_manager: "{{ ansible_facts.services | active_display_manager | default('') }}"

- name: Enable plymouth display manager service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  loop:
    - name: "{{ display_manager }}"
      enabled: no
    - name: "{{ display_manager }}-plymouth"
      enabled: yes
  when: display_manager | length > 0
